version: '3'
services:
    node:
        image: node
        volumes:
            - '.:/content'
        ports:
            - 3000:3000
        command: ['npm', 'run', 'start', '--prefix', '/content']